using Test
using LinearAlgebra: I, kron

include(joinpath(@__DIR__, "ck_physical_kernel_sideband_obstruction.jl"))
include(joinpath(@__DIR__, "ck_physical_b2_kernel_bridge.jl"))

const CKRotatingBridgeExact = Complex{Rational{Int}}
const ck_rotating_bridge_im = CKRotatingBridgeExact(0 // 1, 1 // 1)

function ck_bloch_two_jump_period_polynomial(first_mismatch::Int, second_mismatch::Int)
  # exp(LB): the secular B1^2/2 contribution.
  if iszero(first_mismatch) && iszero(second_mismatch)
    return CKRotatingBridgeExact[0, 0, 1 // 2]
  end

  result = CKRotatingBridgeExact[0, 0]

  # L B2^[2]: the zero-total-mismatch slow kernel generated by the Bernoulli
  # homological inverse certified in #217.
  if !iszero(first_mismatch) && iszero(first_mismatch + second_mismatch)
    result[2] += ck_physical_b2_inverse_weight(first_mismatch)
  end

  # L[X1(t0),B1]: endpoint micromotion. The model leg has zero mismatch;
  # the complementary leg carries the nonzero mismatch through X1.
  if iszero(first_mismatch) && !iszero(second_mismatch)
    result[2] += ck_physical_b2_inverse_weight(second_mismatch)
  elseif !iszero(first_mismatch) && iszero(second_mismatch)
    result[2] -= ck_physical_b2_inverse_weight(first_mismatch)
  end

  return result
end

function ck_rotating_bridge_fixture()
  sigma_x = CKRotatingBridgeExact[0 1; 1 0]
  sigma_y = CKRotatingBridgeExact[0 -ck_rotating_bridge_im; ck_rotating_bridge_im 0]
  sigma_z = CKRotatingBridgeExact[1 0; 0 -1]
  sigma_minus = (1 // 2) * (sigma_x - ck_rotating_bridge_im * sigma_y)
  sigma_plus = (1 // 2) * (sigma_x + ck_rotating_bridge_im * sigma_y)
  identity_component = Matrix{CKRotatingBridgeExact}(I, 2, 2)
  amplitudes = Dict(
    0 => sigma_z,
    1 => ck_rotating_bridge_im * sigma_minus,
    -1 => -ck_rotating_bridge_im * sigma_plus,
  )
  return (; amplitudes, identity_component, sigma_z)
end

function ck_rotating_bridge_recycling(
  left::Matrix{CKRotatingBridgeExact}, right::Matrix{CKRotatingBridgeExact}
)
  return kron(conj.(right), left)
end

function ck_rotating_bridge_hamiltonian_super(H::Matrix{CKRotatingBridgeExact})
  identity_component = Matrix{CKRotatingBridgeExact}(I, 2, 2)
  return -ck_rotating_bridge_im *
         (kron(identity_component, H) - kron(transpose(H), identity_component))
end

function ck_rotating_bridge_accumulate!(
  polynomial::Vector{Matrix{CKRotatingBridgeExact}},
  coefficients::Vector{CKRotatingBridgeExact},
  value::Matrix{CKRotatingBridgeExact},
)
  length(polynomial) >= length(coefficients) ||
    append!(
      polynomial,
      [zero(first(polynomial)) for _ in 1:(length(coefficients) - length(polynomial))],
    )
  for power in eachindex(coefficients)
    polynomial[power] += coefficients[power] * value
  end
  return polynomial
end

function ck_rotating_bridge_zero_polynomial(zero_superoperator)
  return Matrix{CKRotatingBridgeExact}[copy(zero_superoperator)]
end

function ck_rotating_bridge_coefficient(polynomial, power::Int, zero_superoperator)
  index = power + 1
  return index <= length(polynomial) ? polynomial[index] : zero_superoperator
end

function ck_rotating_bridge_add_power!(polynomial, power::Int, value, zero_superoperator)
  while length(polynomial) < power + 1
    push!(polynomial, copy(zero_superoperator))
  end
  polynomial[power + 1] += value
  return polynomial
end

function ck_rotating_bridge_q2_by_phase(amplitudes, zero_superoperator; overlap)
  resolved = Dict{Int,Vector{Matrix{CKRotatingBridgeExact}}}()
  for (first_left, first_left_value) in amplitudes,
    (second_left, second_left_value) in amplitudes,
    (first_right, first_right_value) in amplitudes,
    (second_right, second_right_value) in amplitudes

    coefficients = overlap(
      first_left - first_right, second_left - second_right
    )
    all(iszero, coefficients) && continue

    phase = first_left + second_left - first_right - second_right
    polynomial = get!(resolved, phase) do
      return ck_rotating_bridge_zero_polynomial(zero_superoperator)
    end
    left_value = second_left_value * first_left_value
    right_value = second_right_value * first_right_value
    ck_rotating_bridge_accumulate!(
      polynomial, coefficients, ck_rotating_bridge_recycling(left_value, right_value)
    )
  end
  return resolved
end

function ck_rotating_bridge_q2_by_first_mismatch(amplitudes, zero_superoperator; overlap)
  resolved = Dict{Int,Vector{Matrix{CKRotatingBridgeExact}}}()
  for (first_left, first_left_value) in amplitudes,
    (second_left, second_left_value) in amplitudes,
    (first_right, first_right_value) in amplitudes,
    (second_right, second_right_value) in amplitudes

    first_left + second_left == first_right + second_right || continue
    coefficients = overlap(
      first_left - first_right, second_left - second_right
    )
    all(iszero, coefficients) && continue

    mismatch = abs(first_left - first_right)
    polynomial = get!(resolved, mismatch) do
      return ck_rotating_bridge_zero_polynomial(zero_superoperator)
    end
    left_value = second_left_value * first_left_value
    right_value = second_right_value * first_right_value
    ck_rotating_bridge_accumulate!(
      polynomial, coefficients, ck_rotating_bridge_recycling(left_value, right_value)
    )
  end
  return resolved
end

function ck_rotating_bridge_first_channel(amplitudes, zero_superoperator)
  identity_superoperator = Matrix{CKRotatingBridgeExact}(I, 4, 4)
  recycling_zero = zero_superoperator
  for value in values(amplitudes)
    recycling_zero += ck_rotating_bridge_recycling(value, value)
  end
  polynomial = ck_rotating_bridge_zero_polynomial(zero_superoperator)
  ck_rotating_bridge_add_power!(
    polynomial, 1, recycling_zero - 2 * identity_superoperator, zero_superoperator
  )
  return polynomial, recycling_zero
end

function ck_rotating_bridge_full_second_channel(
  q2_by_phase, recycling_zero, zero_superoperator
)
  resolved = Dict(
    phase => [copy(value) for value in polynomial] for (phase, polynomial) in q2_by_phase
  )
  zero_phase = get!(resolved, 0) do
    return ck_rotating_bridge_zero_polynomial(zero_superoperator)
  end
  identity_superoperator = Matrix{CKRotatingBridgeExact}(I, 4, 4)
  # Q=-I after factoring gamma. The exact scalar no-jump factor e^{-2 gamma T}
  # contributes +2 L^2 I and dresses the one-jump channel by -2 L^2 J0.
  ck_rotating_bridge_add_power!(
    zero_phase,
    2,
    2 * identity_superoperator - 2 * recycling_zero,
    zero_superoperator,
  )
  return resolved
end

function ck_rotating_bridge_polynomial_product(left, right, zero_superoperator)
  result = ck_rotating_bridge_zero_polynomial(zero_superoperator)
  for left_index in eachindex(left), right_index in eachindex(right)
    left_power = left_index - 1
    right_power = right_index - 1
    ck_rotating_bridge_add_power!(
      result,
      left_power + right_power,
      left[left_index] * right[right_index],
      zero_superoperator,
    )
  end
  return result
end

@testset "Bloch period reconstruction equals the exact two-jump simplex kernel" begin
  for first_mismatch in -12:12, second_mismatch in -12:12
    @test ck_bloch_two_jump_period_polynomial(first_mismatch, second_mismatch) ==
      two_jump_period_polynomial(first_mismatch, second_mismatch)
  end

  # Pin each distinct BF contribution separately.
  @test ck_bloch_two_jump_period_polynomial(0, 0) ==
    CKRotatingBridgeExact[0, 0, 1 // 2]
  @test ck_bloch_two_jump_period_polynomial(2, -2) ==
    CKRotatingBridgeExact[0, ck_rotating_bridge_im / 2]
  @test ck_bloch_two_jump_period_polynomial(0, 3) ==
    CKRotatingBridgeExact[0, ck_rotating_bridge_im / 3]
  @test ck_bloch_two_jump_period_polynomial(3, 0) ==
    CKRotatingBridgeExact[0, -ck_rotating_bridge_im / 3]
  @test all(iszero, ck_bloch_two_jump_period_polynomial(2, 3))
end

@testset "Bloch physical kernel reproduces the complete rotating-jump channel/log oracle" begin
  fixture = ck_rotating_bridge_fixture()
  zero_superoperator = zeros(CKRotatingBridgeExact, 4, 4)

  q2_bloch = ck_rotating_bridge_q2_by_phase(
    fixture.amplitudes,
    zero_superoperator;
    overlap=ck_bloch_two_jump_period_polynomial,
  )
  q2_direct = ck_rotating_bridge_q2_by_phase(
    fixture.amplitudes,
    zero_superoperator;
    overlap=two_jump_period_polynomial,
  )

  @test sort!(collect(keys(q2_bloch))) == [-2, -1, 0, 1, 2]
  @test keys(q2_bloch) == keys(q2_direct)
  for phase in keys(q2_direct)
    @test q2_bloch[phase] == q2_direct[phase]
  end

  first_channel, recycling_zero = ck_rotating_bridge_first_channel(
    fixture.amplitudes, zero_superoperator
  )
  second_channel = ck_rotating_bridge_full_second_channel(
    q2_bloch, recycling_zero, zero_superoperator
  )

  @test sort!(collect(keys(second_channel))) == [-2, -1, 0, 1, 2]
  @test iszero(ck_rotating_bridge_coefficient(second_channel[-2], 1, zero_superoperator))
  @test iszero(ck_rotating_bridge_coefficient(second_channel[2], 1, zero_superoperator))
  @test !iszero(ck_rotating_bridge_coefficient(second_channel[-1], 1, zero_superoperator))
  @test !iszero(ck_rotating_bridge_coefficient(second_channel[1], 1, zero_superoperator))

  first_square = ck_rotating_bridge_polynomial_product(
    first_channel, first_channel, zero_superoperator
  )
  log_zero_phase = [copy(value) for value in second_channel[0]]
  for power in 0:(length(first_square) - 1)
    ck_rotating_bridge_add_power!(
      log_zero_phase,
      power,
      -(1 // 2) * ck_rotating_bridge_coefficient(first_square, power, zero_superoperator),
      zero_superoperator,
    )
  end

  @test iszero(ck_rotating_bridge_coefficient(log_zero_phase, 2, zero_superoperator))
  expected = ck_rotating_bridge_hamiltonian_super(-(5 // 4) * fixture.sigma_z)
  @test ck_rotating_bridge_coefficient(log_zero_phase, 1, zero_superoperator) == expected
end

@testset "Bloch two-output kernel resolves the physical -1 and -1/4 RR pieces" begin
  fixture = ck_rotating_bridge_fixture()
  zero_superoperator = zeros(CKRotatingBridgeExact, 4, 4)
  rr = ck_rotating_bridge_q2_by_first_mismatch(
    fixture.amplitudes,
    zero_superoperator;
    overlap=ck_bloch_two_jump_period_polynomial,
  )

  @test sort!(collect(keys(rr))) == [0, 1, 2]
  @test iszero(ck_rotating_bridge_coefficient(rr[0], 1, zero_superoperator))

  m1 = ck_rotating_bridge_coefficient(rr[1], 1, zero_superoperator)
  m2 = ck_rotating_bridge_coefficient(rr[2], 1, zero_superoperator)
  expected_m1 = ck_rotating_bridge_hamiltonian_super(-fixture.sigma_z)
  expected_m2 = ck_rotating_bridge_hamiltonian_super(-(1 // 4) * fixture.sigma_z)

  @test m1 == expected_m1
  @test m2 == expected_m2
  @test m1 + m2 == ck_rotating_bridge_hamiltonian_super(-(5 // 4) * fixture.sigma_z)
end
