using Test
using FloquetExpansions
using SecondQuantizedAlgebra: SecondQuantizedAlgebra
using Symbolics: @variables

const SQA = SecondQuantizedAlgebra

function cp_hfe_linear_dissipative_sector(expansions, grade::Int)
  plus_one = effective_component(expansions[1], grade)
  minus_one = effective_component(expansions[-1], grade)
  plus_two = effective_component(expansions[2], grade)
  minus_two = effective_component(expansions[-2], grade)

  odd_one = (1 // 2) * (plus_one - minus_one)
  odd_two = (1 // 4) * (plus_two - minus_two)
  return SQA.simplify((1 // 3) * (4 * odd_one - odd_two))
end

@testset "periodic physical jump separates one-R gauge and RR sectors" begin
  pauli = PauliSpace(:cp_hfe_periodic_jump_qubit)
  σx = Pauli(pauli, :sigma, 1)
  σy = Pauli(pauli, :sigma, 2)
  σz = Pauli(pauli, :sigma, 3)
  @variables ω_cp_rr::Real t_cp_rr::Real Δ_cp_rr::Real Ω_cp_rr::Real η_cp_rr::Real

  ω = ω_cp_rr
  t = t_cp_rr
  Δ = Δ_cp_rr
  Ω = Ω_cp_rr
  η = η_cp_rr

  H = (1 // 2) * Δ * σz + Ω * cos(ω * t) * σx
  rotating_jump = σz + η * (cos(ω * t) * σy + sin(ω * t) * σx)

  H_map = harmonics(hamiltonian_action(H), ω, t)
  R = harmonics(dissipator(rotating_jump), ω, t)

  # Directional modulation, rather than a scalar rate modulation, produces genuinely distinct
  # dissipative harmonics. This physical jump has both first and second sidebands.
  @test sort!(collect(keys(R))) == [-2, -1, 0, 1, 2]
  @test !iszero(SQA.simplify(R[1]))
  @test !iszero(SQA.simplify(R[2]))

  # Polarize the direct Liouvillian Van Vleck result in a bookkeeping scale multiplying the
  # physical dissipator. At grade two the result is cubic in that scale, so the symmetric
  # four-point combination isolates exactly the sector containing one dissipative vertex.
  direct = Dict(
    scale => floquet_expansion(H_map + scale * R, VanVleck(), 3) for scale in (-2, -1, 0, 1, 2)
  )
  one_R_first = cp_hfe_linear_dissipative_sector(direct, 1)
  one_R_second = cp_hfe_linear_dissipative_sector(direct, 2)

  native = FloquetExpansions.cp_hfe_reconstruction(
    H, ω, t, 3, (jump(rotating_jump, 1),)
  )
  native_first =
    (1 / ω) * FloquetExpansions.cp_dissipative_component(native.amplitudes, 1)
  native_second =
    (1 / ω^2) * FloquetExpansions.cp_dissipative_component(native.amplitudes, 2)

  # The complete one-R sector agrees at first order. The extra direct-Liouvillian contribution
  # begins with RR and therefore cannot be generated by coherent transport of a physical jump.
  @test iszero(SQA.simplify(one_R_first - native_first))

  direct_zero_first = effective_component(direct[0], 1)
  direct_plus_first = effective_component(direct[1], 1)
  direct_minus_first = effective_component(direct[-1], 1)
  RR_first = SQA.simplify(
    (1 // 2) * (direct_plus_first + direct_minus_first - 2 * direct_zero_first)
  )
  RR_pure = effective_component(floquet_expansion(R, VanVleck(), 2), 1)

  @test !iszero(SQA.simplify(RR_first))
  @test iszero(SQA.simplify(RR_first - RR_pure))
  @test iszero(
    SQA.simplify(effective_component(floquet_expansion(2 * R, VanVleck(), 2), 1) - 4 * RR_pure)
  )

  # At second order the one-R difference is precisely the certified static similarity generated
  # by B_R^(2). This is distinct from the RR sector above, which already appears at O(γ^2/ω).
  B_R = zero(R[0])
  for harmonic in keys(H_map)
    iszero(harmonic) && continue
    B_R +=
      (1 // (2 * harmonic^2 * ω^2)) *
      SQA.commutator(H_map[harmonic], R[-harmonic])
  end
  gauge_residual = SQA.commutator(B_R, H_map[0])

  @test !iszero(SQA.simplify(B_R))
  @test !iszero(SQA.simplify(gauge_residual))
  @test iszero(SQA.simplify(one_R_second - native_second - gauge_residual))

  # Native CP-HFE remains exactly linear in the physical jump rate: doubling the microscopic
  # rate doubles the reconstructed dissipative generator, so no hidden γ^2 RR term is present.
  native_rate_two = FloquetExpansions.cp_hfe_reconstruction(
    H, ω, t, 3, (jump(rotating_jump, 2),)
  )
  coherent_generator = hamiltonian_action(effective_generator(native.coherent))
  native_dissipative = native.generator - coherent_generator
  native_rate_two_dissipative = native_rate_two.generator - coherent_generator
  @test iszero(SQA.simplify(native_rate_two_dissipative - 2 * native_dissipative))
end
