using Test
using FloquetExpansions
using SecondQuantizedAlgebra: SecondQuantizedAlgebra
using Symbolics: @variables

const SQA = SecondQuantizedAlgebra

function cp_hfe_one_R_second_order_reference(H_map, R)
  h_harmonics = filter(!=(0), collect(keys(H_map)))
  r_harmonics = filter(!=(0), collect(keys(R)))
  three_harmonic_bound = max(2 * maximum(abs, h_harmonics), maximum(abs, r_harmonics))
  three_harmonics = filter(!=(0), collect((-three_harmonic_bound):three_harmonic_bound))
  H0 = H_map[0]
  R0 = R[0]

  B_R = zero(H0)
  V_R_a = zero(H0)
  for m in h_harmonics
    B_R += (1 // (2 * m^2)) * SQA.commutator(H_map[m], R[-m])
    V_R_a -=
      (1 // (2 * m^2)) * (
        SQA.commutator(R[-m], SQA.commutator(H0, H_map[m])) +
        SQA.commutator(H_map[-m], SQA.commutator(R0, H_map[m])) +
        SQA.commutator(H_map[-m], SQA.commutator(H0, R[m]))
      )
  end

  V_R_b = zero(H0)
  for m in three_harmonics, n in three_harmonics
    n == m && continue
    V_R_b -=
      (1 // (3 * n * m)) * (
        SQA.commutator(R[-n], SQA.commutator(H_map[n - m], H_map[m])) +
        SQA.commutator(H_map[-n], SQA.commutator(R[n - m], H_map[m])) +
        SQA.commutator(H_map[-n], SQA.commutator(H_map[n - m], R[m]))
      )
  end

  return SQA.simplify(V_R_a + V_R_b), SQA.simplify(B_R)
end

@testset "periodic physical jump separates one-R gauge and RR sectors" begin
  pauli = PauliSpace(:cp_hfe_periodic_jump_qubit)
  σx = Pauli(pauli, :sigma, 1)
  σy = Pauli(pauli, :sigma, 2)
  σz = Pauli(pauli, :sigma, 3)
  @variables ω_cp_rr::Real t_cp_rr::Real

  ω = ω_cp_rr
  t = t_cp_rr

  # Exact nondegenerate point Δ = 2, Ω = 1, η = 1 of
  # H(t) = Δ σz / 2 + Ω cos(ωt) σx and
  # J(t) = σz + η [cos(ωt) σy + sin(ωt) σx].
  H = σz + cos(ω * t) * σx
  rotating_jump = σz + cos(ω * t) * σy + sin(ω * t) * σx

  H_map = harmonics(hamiltonian_action(H), ω, t)
  R = harmonics(dissipator(rotating_jump), ω, t)

  # Directional modulation, rather than a scalar rate modulation, produces genuinely distinct
  # dissipative harmonics. This physical jump has both first and second sidebands.
  @test sort!(collect(keys(R))) == [-2, -1, 0, 1, 2]
  @test !iszero(SQA.simplify(R[1]))
  @test !iszero(SQA.simplify(R[2]))

  # At first order the direct Liouvillian result splits exactly into a coherent HH sector,
  # the retained one-R sector, and the genuinely additional RR sector.
  direct_total = floquet_expansion(H_map + R, VanVleck(), 2)
  direct_H = floquet_expansion(H_map, VanVleck(), 2)
  direct_R = floquet_expansion(R, VanVleck(), 2)
  total_first = effective_component(direct_total, 1)
  H_first = effective_component(direct_H, 1)
  RR_first = effective_component(direct_R, 1)
  one_R_first = SQA.simplify(total_first - H_first - RR_first)

  native = FloquetExpansions.cp_hfe_reconstruction(H, ω, t, 3, (jump(rotating_jump, 1),))
  native_first = FloquetExpansions.cp_dissipative_component(native.amplitudes, 1)
  native_second = FloquetExpansions.cp_dissipative_component(native.amplitudes, 2)

  @test iszero(SQA.simplify(ω * one_R_first - native_first))
  @test !iszero(SQA.simplify(RR_first))
  @test iszero(
    SQA.simplify(
      effective_component(floquet_expansion(2 * R, VanVleck(), 2), 1) - 4 * RR_first
    ),
  )

  # At second order the complete one-R direct-Liouvillian sector differs from native CP-HFE
  # precisely by the certified static similarity generated by B_R^(2).
  V_R_second, B_R = cp_hfe_one_R_second_order_reference(H_map, R)
  gauge_residual = SQA.commutator(B_R, H_map[0])

  @test !iszero(SQA.simplify(B_R))
  @test !iszero(SQA.simplify(gauge_residual))
  @test iszero(SQA.simplify(V_R_second - native_second - gauge_residual))

  # Native CP-HFE remains exactly linear in the physical jump rate: doubling the microscopic
  # rate doubles the reconstructed dissipative generator, so no hidden γ^2 RR term is present.
  native_rate_two = FloquetExpansions.cp_hfe_reconstruction(
    H, ω, t, 3, (jump(rotating_jump, 2),)
  )
  coherent_generator = hamiltonian_action(effective_generator(native.coherent))
  native_dissipative = native.generator - coherent_generator
  native_rate_two_dissipative = native_rate_two.generator - coherent_generator
  @test iszero(SQA.simplify(native_rate_two_dissipative - 2 * native_dissipative))
end
