name = "FloquetExpansions"
uuid = "3d8c71b5-958b-4b86-b80e-339bb07db863"
version = "0.1.0"
authors = ["Orjan Ameye <orjan.ameye@hotmail.com>"]

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SecondQuantizedAlgebra = "f7aa4685-e143-4cb6-a7f3-073579757907"

[sources]
SecondQuantizedAlgebra = {rev = "main", url = "https://github.com/qojulia/SecondQuantizedAlgebra.jl"}

[compat]
Reexport = "1.2"
SecondQuantizedAlgebra = "0.10.1"
julia = "1.10"
