[deps]
CodeRatchet = "0e86a969-c127-44ad-8bee-7851ffae31d4"
FloquetExpansions = "3d8c71b5-958b-4b86-b80e-339bb07db863"

[sources]
CodeRatchet = {url = "https://github.com/oameye/CodeRatchet.jl", rev = "90cc9753755fcbc1f898939347995cec1ca2f4eb"}
FloquetExpansions = {path = ".."}

[compat]
julia = "1.12"
