# Graded jump amplitudes of the generator-native GKLS expansion.
#
# A channel born at generator order `onset` carries the amplitude series
# ε^(onset/2) Σ_k ε^k r_k, so its contribution to the order-n Kossakowski coefficient is
# Σ_{k+l = n-onset} r_k r_l†. Coefficients are stored in Kossakowski coordinates of a fixed
# operator frame and are generic over the scalar type.

struct GradedChannel{T}
  onset::Int
  coefficients::Vector{Vector{T}}
end

function active_channels(
  channels::AbstractVector{GradedChannel{T}}, order::Int, dimension::Int
) where {T}
  indices = Int[]
  for (index, channel) in pairs(channels)
    channel.onset < order && push!(indices, index)
  end
  active = Matrix{T}(undef, dimension, length(indices))
  for (column, index) in pairs(indices)
    active[:, column] = channels[index].coefficients[1]
  end
  return indices, active
end

hermitian_part(X::AbstractMatrix) = (X + adjoint(X)) / 2

# Products of already known amplitudes entering the order-`order` coefficient: K_n^<.
function known_gram(
  channels::AbstractVector{GradedChannel{T}}, order::Int, dimension::Int
) where {T}
  result = zeros(T, dimension, dimension)
  for channel in channels
    q = order - channel.onset
    q >= 2 || continue
    length(channel.coefficients) >= q ||
      throw(ArgumentError("graded channel is missing a lower-order amplitude"))
    for k in 1:(q - 1)
      result += channel.coefficients[k + 1] * adjoint(channel.coefficients[q - k + 1])
    end
  end
  return hermitian_part(result)
end

# The order-`order` Kossakowski coefficient generated by the amplitudes stored so far.
function gram_coefficient(
  channels::AbstractVector{GradedChannel{T}}, order::Int, dimension::Int
) where {T}
  result = zeros(T, dimension, dimension)
  for channel in channels
    q = order - channel.onset
    stored = length(channel.coefficients)
    for k in max(0, q + 1 - stored):min(q, stored - 1)
      result += channel.coefficients[k + 1] * adjoint(channel.coefficients[q - k + 1])
    end
  end
  return hermitian_part(result)
end

function store_corrections!(
  channels::AbstractVector{GradedChannel{T}},
  indices::AbstractVector{Int},
  correction::AbstractMatrix,
  order::Int,
) where {T}
  size(correction, 2) == length(indices) ||
    throw(DimensionMismatch("one correction column is required per active channel"))
  for (column, index) in pairs(indices)
    channel = channels[index]
    length(channel.coefficients) == order - channel.onset ||
      throw(ArgumentError("graded channel coefficient sequence is not prefix complete"))
    push!(channel.coefficients, Vector{T}(correction[:, column]))
  end
  return channels
end

function store_births!(
  channels::AbstractVector{GradedChannel{T}}, newborn::AbstractMatrix, order::Int
) where {T}
  for column in axes(newborn, 2)
    push!(channels, GradedChannel{T}(order, [Vector{T}(newborn[:, column])]))
  end
  return channels
end
